databaseChangeLog:
  - changeSet:
      id: 001-init-db-structure
      author: navin
      changes:
        - createTable:
            tableName: color
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
              - column:
                  name: name
                  type: VARCHAR(255)

        - createTable:
            tableName: roles
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: date_import
                  type: date
              - column:
                  name: date_import
                  type: date

        - createTable:
            tableName: user_roles
            columns:
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: role_id
                  type: BIGINT
                  constraints:
                    nullable: false

